### ISSUE TITLE
Option to set minimum and maximum number of entries

### ISSUE THREAD

**Issue by GitHunter0** [gagan3012/streamlit-tags#12]
Hey man @gagan3012 , cool extension, this was exactly what I was looking for!

Would you consider adding an option to set the minimum and maximum number of entries allowed?

This is important because usually we use the entries in subsequent analyses and if the number is different from what is expected, things go all wrong.

Thank you

**Comment by gagan3012** [comment]
Hi, @GitHunter0 
Sure that can be implemented soon Do you have any specifications for the Max/min?

**Comment by GitHunter0** [comment]
Cool @gagan3012 . 
No, nothing special, I just don't want the user to insert more than four and less than two elements, for example.
Surely I can always adjust the code to correct for this, it is not a big deal. But it would be nice to have this limitation set natively in the widget.

**Comment by gagan3012** [comment]
Hi, 
I have added the maxtags param for st_tags and st_tags_sidebar please upgrade to 1.1.9

**Comment by GitHunter0** [comment]
Great man! The feature is working fine, thank you for the effort.

PS: I could not install via `conda install --channel=gagan3012 streamlit-tags`, it is still at version 1.1.7. But via `Pip` it worked.
