### ISSUE TITLE
Text is not displayed completely

### ISSUE THREAD

**Issue by GitHunter0** [gagan3012/streamlit-tags#13]
Hey @gagan3012 , just one more thing.

Although there is enough space, the text argument (in this case 'Press enter to add up to 3 keywords') is not displayed completely, it is truncated at "Press enter to add up to" as shown by the picture below

![image](https://user-images.githubusercontent.com/26294221/116166954-956b1580-a6d5-11eb-9a15-8b8e83b9fcd7.png)

**Comment by gagan3012** [comment]
Hey @GitHunter0 
I have fixed it in the latest update

**Comment by GitHunter0** [comment]
Thanks man, problem solved!
