### ISSUE TITLE
Component Erro

### ISSUE THREAD

**Issue by ravinpoudel** [gagan3012/streamlit-tags#17]
Component Error
E.map is not a function. (In 'E.map((function(e){return a.a.createElement(b,{key:e,text:e,remove:S})}))', 'E.map' is undefined)
<img width="325" alt="Screen Shot 2021-05-05 at 4 12 54 PM" src="https://user-images.githubusercontent.com/25137267/117203225-c37ae480-adbc-11eb-91f8-ca1e11a106fb.png">

I am not sure to fix this issue. Any suggestions?

**Comment by gagan3012** [comment]
Hello, 
I haven't seen this error before but rebooting the app might help

**Comment by ravinpoudel** [comment]
Thanks.... tried with rebooting and installing again. Same issue still persists. `E.map is not a function` not sure where is this coming from -- either a bug in `streamlit` or in `streamlet-tags`. I am on 0.80.0 for  `streamlit` and `1.1.9` version for `streamlet-tags`.

**Comment by gagan3012** [comment]
Can you please share the code on how you are calling st_sidebar_tags

**Comment by ravinpoudel** [comment]
``` 
restriction_enzyme_list = st_tags_sidebar('Restriction Enzymes[e.g. NGRT]:', 'Enter to add more', ['NGRT'])
 
```

**Comment by gagan3012** [comment]
Hello, 
I have figured it out, in one of the latest releases the order of the variables changed and I would recommend you to reference the variables by name instead of position like: 
```
restriction_enzyme_list = st_tags_sidebar(label = 'Restriction Enzymes[e.g. NGRT]:',
                                                                  text  = 'Enter to add more', 
                                                                  value = ['NGRT'])
```

**Comment by ravinpoudel** [comment]
Thanks @gagan3012 ...now it works smoothly. Really appreciate for such a quick reply and solution.
