### ISSUE TITLE
Feature Request: AutoComplete

### ISSUE THREAD

**Issue by isConic** [gagan3012/streamlit-tags#4]
**Is your feature request related to a problem? Please describe.**
Lets say I have two possible labels  [cat and dog], seeing a list of pre-existing tags would aid a user in selecting pre-known tags rather than typing "feline" or "pitbull"   

**Describe the solution you'd like**
Text auto-complete to show me possible tags.   

Here is an example: 
![](https://www.jqueryscript.net/images/Dynamic-Autocomplete-Tag-Input-Plugin-For-jQuery-Tokenize2.jpg)

Syntax: 
```python
keywords = st_tags('Enter Keyword:',
        'Press enter to add more',
        ["animal"], key_hints = ["cat", "dog"] )
```

**Comment by gagan3012** [comment]
Still working on this Feature will close when done

**Comment by gagan3012** [comment]
Hello, this feature has been implemented 
Please upgrade streamlit-tags to 1.1.3

and try the following line of code: 
```
keywords = st_tags(label='# Enter Keywords:',
                   text='Press enter to add more',
                   value=['Zero', 'One', 'Two'],
                   suggestions=['five', 'six', 'seven', 'eight', 'nine', 'three', 'eleven', 'ten', 'four'])
```
