### ISSUE TITLE
Support [brand new] Streamlit themes .79

### ISSUE THREAD

**Issue by jeremyabramson** [gagan3012/streamlit-tags#5]
Streamlit just released custom themes (https://docs.streamlit.io/en/stable/changelog.html).  It'd be great if the tags widget respected the theme colors.

Also, the main "label" text seems larger than normal widgets.

**Comment by gagan3012** [comment]
Hello, Streamlit_tags now supports the new streamlit themes Please upgrade is 1.0.7 version
