### ISSUE TITLE
Tags background not displayed, and sidebar text size seems little big that the other

### ISSUE THREAD

**Issue by ravinpoudel** [gagan3012/streamlit-tags#7]
Thanks fro developing this component for streamlit. However, I am missing the background color from the tags, and text size seems little off - for  `st_tags_sidebar`
<img width="316" alt="Screen Shot 2021-04-07 at 5 05 28 PM" src="https://user-images.githubusercontent.com/25137267/113934400-b4a41080-97c3-11eb-9033-ac62feab061a.png">

For example: The text size for `Restriction Enzymes[E.g. NGRT]` is bigger than the text above `Input PAM....`

I am using:  streamlit-tags  version 1.1.4

**Comment by gagan3012** [comment]
Hello, 
Can you share the .streamlit/config.toml file too? 
I have just pushed a fix for the sizing issue.

**Comment by gagan3012** [comment]
Please upgrade to streamlit-tags 1.1.5

**Comment by ravinpoudel** [comment]
where can I find .streamlit/config.toml  file?

Thanks for such a quick support.

**Comment by ravinpoudel** [comment]
Hi @gagan3012 , I updated the version of streamlit, and it solved the background issues. Thanks!!!

**Comment by gagan3012** [comment]
Okay that's great!

Also check out: https://share.streamlit.io/gagan3012/streamlit-tags/examples/app.py for further reference
