### ISSUE TITLE
Conda installation

### ISSUE THREAD

**Issue by ravinpoudel** [gagan3012/streamlit-tags#8]
Is there a conda installation for streamlit-tags? If not is it possible to make it available? I really like streamlit-tags feature, and works great for my need/project. However, I am using bioconda for packaging my script, and getting ` conda_build.exceptions.DependencyNeedsBuildingError`.

**Comment by gagan3012** [comment]
Hello,
How are you installing streamlit tags?
I am working on a conda distribution

**Comment by ravinpoudel** [comment]
When I am running my software locally, I am creating a Conda environment and install the dependencies within conda env. For streamlet-tag: `pip install streamlit-tags` within in conda env. I am planning to package my code and deploy as conda package via bio-conda, and is where I am getting `conda_build.exceptions.DependencyNeedsBuildingError.`

**Comment by gagan3012** [comment]
Try using this:
```
pip install -i https://pypi.anaconda.org/gagan3012/simple streamlit-tags
```

**Comment by ravinpoudel** [comment]
Any suggestion on how to specify it in `setup.py` or conda recipe file `meta.yaml`??

**Comment by gagan3012** [comment]
Hi Can you share the entire error that you get? did the above code solve the issue?

**Comment by ravinpoudel** [comment]
https://github.com/ravinpoudel/GuideMaker/runs/2325413979?check_suite_focus=true

**Comment by gagan3012** [comment]
Can you please try this approach: 

https://stackoverflow.com/questions/38209848/how-to-make-conda-installer-look-for-pypi-packages

**Comment by ravinpoudel** [comment]
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Source cache directory is: /Users/admin/opt/anaconda3/envs/src/conda-bld/src_cache
INFO:conda_build.source:Source cache directory is: /Users/admin/opt/anaconda3/envs/src/conda-bld/src_cache
INFO conda_build.source:download_to_cache(44): Source cache directory is: /Users/admin/opt/anaconda3/envs/src/conda-bld/src_cache
Downloading source to cache: streamlit-tags-1.1.5_7953dccd65.tar.gz
INFO:conda_build.source:Downloading source to cache: streamlit-tags-1.1.5_7953dccd65.tar.gz
INFO conda_build.source:download_to_cache(69): Downloading source to cache: streamlit-tags-1.1.5_7953dccd65.tar.gz
Downloading https://pypi.io/packages/source/s/streamlit-tags/streamlit-tags-1.1.5.tar.gz
INFO:conda_build.source:Downloading https://pypi.io/packages/source/s/streamlit-tags/streamlit-tags-1.1.5.tar.gz
INFO conda_build.source:download_to_cache(83): Downloading https://pypi.io/packages/source/s/streamlit-tags/streamlit-tags-1.1.5.tar.gz
Error: HTTP 404 NOT FOUND for url <https://pypi.io/packages/source/s/streamlit-tags/streamlit-tags-1.1.5.tar.gz>
Elapsed: 00:00.197536

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
WARNING:conda_build.source:Error: HTTP 404 NOT FOUND for url <https://pypi.io/packages/source/s/streamlit-tags/streamlit-tags-1.1.5.tar.gz>
Elapsed: 00:00.197536

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
WARNING conda_build.source:download_to_cache(87): Error: HTTP 404 NOT FOUND for url <https://pypi.io/packages/source/s/streamlit-tags/streamlit-tags-1.1.5.tar.gz>
Elapsed: 00:00.197536

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
Could not download https://pypi.io/packages/source/s/streamlit-tags/streamlit-tags-1.1.5.tar.gz
(src) 🙏

**Comment by gagan3012** [comment]
Can you try this: 
```
conda skeleton pypi streamlit-tags
```

**Comment by ravinpoudel** [comment]
still I am getting the same error:

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK

done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Source cache directory is: /Users/admin/opt/anaconda3/envs/src/conda-bld/src_cache
INFO:conda_build.source:Source cache directory is: /Users/admin/opt/anaconda3/envs/src/conda-bld/src_cache
INFO conda_build.source:download_to_cache(44): Source cache directory is: /Users/admin/opt/anaconda3/envs/src/conda-bld/src_cache
Downloading source to cache: streamlit-tags-1.1.5_7953dccd65.tar.gz
INFO:conda_build.source:Downloading source to cache: streamlit-tags-1.1.5_7953dccd65.tar.gz
INFO conda_build.source:download_to_cache(69): Downloading source to cache: streamlit-tags-1.1.5_7953dccd65.tar.gz
Downloading https://pypi.io/packages/source/s/streamlit-tags/streamlit-tags-1.1.5.tar.gz
INFO:conda_build.source:Downloading https://pypi.io/packages/source/s/streamlit-tags/streamlit-tags-1.1.5.tar.gz
INFO conda_build.source:download_to_cache(83): Downloading https://pypi.io/packages/source/s/streamlit-tags/streamlit-tags-1.1.5.tar.gz
Error: HTTP 404 NOT FOUND for url <https://pypi.io/packages/source/s/streamlit-tags/streamlit-tags-1.1.5.tar.gz>
Elapsed: 00:00.196037

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
WARNING:conda_build.source:Error: HTTP 404 NOT FOUND for url <https://pypi.io/packages/source/s/streamlit-tags/streamlit-tags-1.1.5.tar.gz>
Elapsed: 00:00.196037

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
WARNING conda_build.source:download_to_cache(87): Error: HTTP 404 NOT FOUND for url <https://pypi.io/packages/source/s/streamlit-tags/streamlit-tags-1.1.5.tar.gz>
Elapsed: 00:00.196037

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
Could not download https://pypi.io/packages/source/s/streamlit-tags/streamlit-tags-1.1.5.tar.gz

**Comment by gagan3012** [comment]
Can you share the code you ran to get this error?

**Comment by ravinpoudel** [comment]
Here are the steps I followed:

```
#1. First installed streamlet-tag in a conda env following:
pip install -i https://pypi.anaconda.org/gagan3012/simple streamlit-tags

#2. conda skeleton pypi streamlit-tags

#3. conda-build streamlit-tags

```

**Comment by gagan3012** [comment]
Can you try just 
```
conda skeleton pypi streamlit-tags
conda-build streamlit-tags
```

**Comment by ravinpoudel** [comment]
Sure!!! Any change you are planning to get it to anaconda ? so that it will be much easier to maintain? Something like `conda install streamlit-tags` will be great? I am wondering if the component that you have developed will be a part of streamlit soon or later? Allows to get all just by installing one package.

**Comment by gagan3012** [comment]
I am working on bringing it to Anaconda I am not sure whether this will be merged into streamlit anytime soon, Let me know if this approach worked for you or not

**Comment by ravinpoudel** [comment]
(base) 🙏 conda skeleton pypi streamlit-tags
/Users/admin/opt/anaconda3/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
Warning, the following versions were found for streamlit-tags
0.1.2
1.0.0
1.0.1
1.0.2
1.0.3
1.0.4
1.0.5
1.0.6
1.0.7
1.0.8
1.1.1
1.1.2
1.1.3
1.1.4
1.1.5
Using 1.1.5
Use --version to specify a different version.
Using url https://files.pythonhosted.org/packages/83/d9/bdf362c3871cbc6a76f4e0ef7bf46a202c1951efc8d5c51c08054c727c88/streamlit_tags-1.1.5.tar.gz (545 KB) for streamlit-tags.
Downloading streamlit-tags
PyPI URL:  https://files.pythonhosted.org/packages/83/d9/bdf362c3871cbc6a76f4e0ef7bf46a202c1951efc8d5c51c08054c727c88/streamlit_tags-1.1.5.tar.gz
Using cached download
Unpacking streamlit-tags...
done
working in /var/folders/ct/2nl65wtn3978tk0rq17mg2fw0000gn/T/tmpl6zdlx2econda_skeleton_streamlit_tags-1.1.5.tar.gz
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /Users/admin/opt/anaconda3/conda-bld/skeleton_1618265531545/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol


The following NEW packages will be INSTALLED:

    ca-certificates: 2020.12.5-h033912b_0     conda-forge
    certifi:         2020.12.5-py38h50d1736_1 conda-forge
    libcxx:          11.1.0-habf9029_0        conda-forge
    libffi:          3.3-h046ec9c_2           conda-forge
    ncurses:         6.2-h2e338ed_4           conda-forge
    openssl:         1.1.1k-h0d85af4_0        conda-forge
    pip:             21.0.1-pyhd8ed1ab_0      conda-forge
    python:          3.8.8-h4e93d89_0_cpython conda-forge
    python_abi:      3.8-1_cp38               conda-forge
    pyyaml:          5.4.1-py38h5406a74_0     conda-forge
    readline:        8.1-h05e3726_0           conda-forge
    setuptools:      49.6.0-py38h50d1736_3    conda-forge
    sqlite:          3.35.4-h44b9ce1_0        conda-forge
    tk:              8.6.10-h0419947_1        conda-forge
    wheel:           0.36.2-pyhd3deb0d_0      conda-forge
    xz:              5.2.5-haf1e3a3_1         conda-forge
    yaml:            0.2.5-haf1e3a3_0         conda-forge
    zlib:            1.2.11-h7795811_1010     conda-forge

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Applying patch: '/var/folders/ct/2nl65wtn3978tk0rq17mg2fw0000gn/T/tmpl6zdlx2econda_skeleton_streamlit_tags-1.1.5.tar.gz/pypi-distutils.patch'
Trying to apply patch as-is
INFO:conda_build.source:Trying to apply patch as-is
INFO conda_build.source:apply_patch(596): Trying to apply patch as-is
patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 1 line).
Writing recipe for streamlit-tags
--dirty flag and --keep-old-work not specified. Removing build/test folder after successful build/test.

INFO:conda_build.config:--dirty flag and --keep-old-work not specified. Removing build/test folder after successful build/test.

INFO conda_build.config:__exit__(800): --dirty flag and --keep-old-work not specified. Removing build/test folder after successful build/test.

(base) 🙏 
(base) 🙏 
(base) 🙏 
(base) 🙏 ls
streamlit-tags
(base) 🙏 conda-build streamlit-tags
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for streamlit-tags
INFO:conda_build.metadata:Attempting to finalize metadata for streamlit-tags
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
BUILD START: ['streamlit-tags-1.1.5-py38_0.tar.bz2']
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /Users/admin/opt/anaconda3/conda-bld/streamlit-tags_1618265768342/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl


The following NEW packages will be INSTALLED:

    abseil-cpp:                    20210324.0-he49afe7_0     conda-forge
    altair:                        4.1.0-py_1                conda-forge
    appnope:                       0.1.2-py38h50d1736_1      conda-forge
    argh:                          0.26.2-pyh9f0ad1d_1002    conda-forge
    argon2-cffi:                   20.1.0-py38h5406a74_2     conda-forge
    arrow-cpp:                     3.0.0-py38hbb63ffc_11_cpu conda-forge
    astor:                         0.8.1-pyh9f0ad1d_0        conda-forge
    async_generator:               1.10-py_0                 conda-forge
    attrs:                         20.3.0-pyhd3deb0d_0       conda-forge
    aws-c-cal:                     0.4.5-h07979c6_8          conda-forge
    aws-c-common:                  0.5.2-h0d85af4_0          conda-forge
    aws-c-event-stream:            0.2.7-h7899ccf_1          conda-forge
    aws-c-io:                      0.9.1-h511c4bf_1          conda-forge
    aws-checksums:                 0.1.11-h511c4bf_3         conda-forge
    aws-sdk-cpp:                   1.8.151-h7784011_1        conda-forge
    backcall:                      0.2.0-pyh9f0ad1d_0        conda-forge
    backports:                     1.0-py_2                  conda-forge
    backports.functools_lru_cache: 1.6.4-pyhd8ed1ab_0        conda-forge
    base58:                        2.1.0-pyhd8ed1ab_0        conda-forge
    bleach:                        3.3.0-pyh44b312d_0        conda-forge
    blinker:                       1.4-py_1                  conda-forge
    boto3:                         1.17.49-pyhd8ed1ab_0      conda-forge
    botocore:                      1.20.49-pyhd8ed1ab_0      conda-forge
    brotli:                        1.0.9-h046ec9c_4          conda-forge
    brotlipy:                      0.7.0-py38h5406a74_1001   conda-forge
    bzip2:                         1.0.8-hc929b4f_4          conda-forge
    c-ares:                        1.17.1-h0d85af4_1         conda-forge
    ca-certificates:               2020.12.5-h033912b_0      conda-forge
    cachetools:                    4.2.1-pyhd8ed1ab_0        conda-forge
    certifi:                       2020.12.5-py38h50d1736_1  conda-forge
    cffi:                          1.14.5-py38ha97d567_0     conda-forge
    chardet:                       4.0.0-py38h50d1736_1      conda-forge
    click:                         7.1.2-pyh9f0ad1d_0        conda-forge
    cryptography:                  3.4.7-py38h1fa4640_0      conda-forge
    decorator:                     5.0.6-pyhd8ed1ab_0        conda-forge
    defusedxml:                    0.7.1-pyhd8ed1ab_0        conda-forge
    entrypoints:                   0.3-pyhd8ed1ab_1003       conda-forge
    freetype:                      2.10.4-h4cff582_1         conda-forge
    gflags:                        2.2.2-hb1e8313_1004       conda-forge
    gitdb:                         4.0.7-pyhd8ed1ab_0        conda-forge
    gitpython:                     3.1.14-pyhd8ed1ab_0       conda-forge
    glog:                          0.4.0-hb7f4fc5_3          conda-forge
    grpc-cpp:                      1.37.0-h541e7bd_1         conda-forge
    idna:                          2.10-pyh9f0ad1d_0         conda-forge
    importlib-metadata:            3.10.0-py38h50d1736_0     conda-forge
    ipykernel:                     5.5.3-py38h6c79ece_0      conda-forge
    ipython:                       7.22.0-py38h6c79ece_0     conda-forge
    ipython_genutils:              0.2.0-py_1                conda-forge
    ipywidgets:                    7.6.3-pyhd3deb0d_0        conda-forge
    jedi:                          0.18.0-py38h50d1736_2     conda-forge
    jinja2:                        2.11.3-pyh44b312d_0       conda-forge
    jmespath:                      0.10.0-pyh9f0ad1d_0       conda-forge
    jpeg:                          9d-hbcb3906_0             conda-forge
    jsonschema:                    3.2.0-pyhd8ed1ab_3        conda-forge
    jupyter_client:                6.1.12-pyhd8ed1ab_0       conda-forge
    jupyter_core:                  4.7.1-py38h50d1736_0      conda-forge
    jupyterlab_pygments:           0.1.2-pyh9f0ad1d_0        conda-forge
    jupyterlab_widgets:            1.0.0-pyhd8ed1ab_1        conda-forge
    krb5:                          1.17.2-h60d9502_0         conda-forge
    lcms2:                         2.12-h577c468_0           conda-forge
    libblas:                       3.9.0-8_openblas          conda-forge
    libcblas:                      3.9.0-8_openblas          conda-forge
    libcurl:                       7.76.0-h8ef9fac_0         conda-forge
    libcxx:                        11.1.0-habf9029_0         conda-forge
    libedit:                       3.1.20191231-h0678c8f_2   conda-forge
    libev:                         4.33-haf1e3a3_1           conda-forge
    libevent:                      2.1.10-hddc9c9b_3         conda-forge
    libffi:                        3.3-h046ec9c_2            conda-forge
    libgfortran:                   5.0.0-9_3_0_h6c81a4c_22   conda-forge
    libgfortran5:                  9.3.0-h6c81a4c_22         conda-forge
    liblapack:                     3.9.0-8_openblas          conda-forge
    libnghttp2:                    1.43.0-h07e645a_0         conda-forge
    libopenblas:                   0.3.12-openmp_h54245bb_1  conda-forge
    libpng:                        1.6.37-h7cec526_2         conda-forge
    libprotobuf:                   3.15.8-hcf210ce_0         conda-forge
    libsodium:                     1.0.18-hbcb3906_1         conda-forge
    libssh2:                       1.9.0-h52ee1ee_6          conda-forge
    libthrift:                     0.14.1-hab56fdc_1         conda-forge
    libtiff:                       4.2.0-h355d032_0          conda-forge
    libutf8proc:                   2.6.1-h35c211d_0          conda-forge
    libwebp-base:                  1.2.0-h0d85af4_2          conda-forge
    llvm-openmp:                   11.1.0-hda6cdc1_1         conda-forge
    lz4-c:                         1.9.3-h046ec9c_0          conda-forge
    markupsafe:                    1.1.1-py38h5406a74_3      conda-forge
    mistune:                       0.8.4-py38h5406a74_1003   conda-forge
    nbclient:                      0.5.3-pyhd8ed1ab_0        conda-forge
    nbconvert:                     6.0.7-py38h50d1736_3      conda-forge
    nbformat:                      5.1.3-pyhd8ed1ab_0        conda-forge
    ncurses:                       6.2-h2e338ed_4            conda-forge
    nest-asyncio:                  1.5.1-pyhd8ed1ab_0        conda-forge
    notebook:                      6.3.0-py38h50d1736_0      conda-forge
    numpy:                         1.20.2-py38had91d27_0     conda-forge
    olefile:                       0.46-pyh9f0ad1d_1         conda-forge
    openjpeg:                      2.4.0-h6cbf5cd_0          conda-forge
    openssl:                       1.1.1k-h0d85af4_0         conda-forge
    orc:                           1.6.7-hb8e0f11_1          conda-forge
    packaging:                     20.9-pyh44b312d_0         conda-forge
    pandas:                        1.2.3-py38h1588c1c_0      conda-forge
    pandoc:                        2.13-h0d85af4_0           conda-forge
    pandocfilters:                 1.4.2-py_1                conda-forge
    parquet-cpp:                   1.5.1-2                   conda-forge
    parso:                         0.8.2-pyhd8ed1ab_0        conda-forge
    pexpect:                       4.8.0-pyh9f0ad1d_2        conda-forge
    pickleshare:                   0.7.5-py_1003             conda-forge
    pillow:                        8.1.2-py38h83525de_1      conda-forge
    pip:                           21.0.1-pyhd8ed1ab_0       conda-forge
    prometheus_client:             0.10.1-pyhd8ed1ab_0       conda-forge
    prompt-toolkit:                3.0.18-pyha770c72_0       conda-forge
    protobuf:                      3.15.8-py38ha048514_0     conda-forge
    ptyprocess:                    0.7.0-pyhd3deb0d_0        conda-forge
    pyarrow:                       3.0.0-py38hf787c1d_11_cpu conda-forge
    pycparser:                     2.20-pyh9f0ad1d_2         conda-forge
    pydeck:                        0.6.1-pyh44b312d_0        conda-forge
    pygments:                      2.8.1-pyhd8ed1ab_0        conda-forge
    pyopenssl:                     20.0.1-pyhd8ed1ab_0       conda-forge
    pyparsing:                     2.4.7-pyh9f0ad1d_0        conda-forge
    pyrsistent:                    0.17.3-py38h5406a74_2     conda-forge
    pysocks:                       1.7.1-py38h50d1736_3      conda-forge
    python:                        3.8.8-h4e93d89_0_cpython  conda-forge
    python-dateutil:               2.8.1-py_0                conda-forge
    python_abi:                    3.8-1_cp38                conda-forge
    pytz:                          2021.1-pyhd8ed1ab_0       conda-forge
    pyyaml:                        5.4.1-py38h5406a74_0      conda-forge
    pyzmq:                         22.0.3-py38hd3b92b6_1     conda-forge
    re2:                           2021.04.01-he49afe7_0     conda-forge
    readline:                      8.1-h05e3726_0            conda-forge
    requests:                      2.25.1-pyhd3deb0d_0       conda-forge
    s3transfer:                    0.3.6-pyhd8ed1ab_0        conda-forge
    send2trash:                    1.5.0-py_0                conda-forge
    setuptools:                    49.6.0-py38h50d1736_3     conda-forge
    six:                           1.15.0-pyh9f0ad1d_0       conda-forge
    smmap:                         3.0.5-pyh44b312d_0        conda-forge
    snappy:                        1.1.8-hb1e8313_3          conda-forge
    sqlite:                        3.35.4-h44b9ce1_0         conda-forge
    streamlit:                     0.80.0-pyhd8ed1ab_0       conda-forge
    terminado:                     0.9.4-py38h50d1736_0      conda-forge
    testpath:                      0.4.4-py_0                conda-forge
    tk:                            8.6.10-h0419947_1         conda-forge
    toml:                          0.10.2-pyhd8ed1ab_0       conda-forge
    toolz:                         0.11.1-py_0               conda-forge
    tornado:                       6.1-py38h5406a74_1        conda-forge
    traitlets:                     5.0.5-py_0                conda-forge
    tzlocal:                       2.1-pyh9f0ad1d_0          conda-forge
    urllib3:                       1.26.4-pyhd8ed1ab_0       conda-forge
    validators:                    0.18.2-pyhd3deb0d_0       conda-forge
    watchdog:                      2.0.2-py38h3c40b66_0      conda-forge
    wcwidth:                       0.2.5-pyh9f0ad1d_2        conda-forge
    webencodings:                  0.5.1-py_1                conda-forge
    wheel:                         0.36.2-pyhd3deb0d_0       conda-forge
    widgetsnbextension:            3.5.1-py38h50d1736_4      conda-forge
    xz:                            5.2.5-haf1e3a3_1          conda-forge
    yaml:                          0.2.5-haf1e3a3_0          conda-forge
    zeromq:                        4.3.4-h1c7c35f_0          conda-forge
    zipp:                          3.4.1-pyhd8ed1ab_0        conda-forge
    zlib:                          1.2.11-h7795811_1010      conda-forge
    zstd:                          1.4.9-h582d3a0_0          conda-forge

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... b'Enabling notebook extension jupyter-js-widgets/extension...\n      - Validating: \x1b[32mOK\x1b[0m\n'
done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Source cache directory is: /Users/admin/opt/anaconda3/conda-bld/src_cache
INFO:conda_build.source:Source cache directory is: /Users/admin/opt/anaconda3/conda-bld/src_cache
INFO conda_build.source:download_to_cache(43): Source cache directory is: /Users/admin/opt/anaconda3/conda-bld/src_cache
Downloading source to cache: streamlit-tags-1.1.5_7953dccd65.tar.gz
INFO:conda_build.source:Downloading source to cache: streamlit-tags-1.1.5_7953dccd65.tar.gz
INFO conda_build.source:download_to_cache(66): Downloading source to cache: streamlit-tags-1.1.5_7953dccd65.tar.gz
Downloading https://pypi.io/packages/source/s/streamlit-tags/streamlit-tags-1.1.5.tar.gz
INFO:conda_build.source:Downloading https://pypi.io/packages/source/s/streamlit-tags/streamlit-tags-1.1.5.tar.gz
INFO conda_build.source:download_to_cache(80): Downloading https://pypi.io/packages/source/s/streamlit-tags/streamlit-tags-1.1.5.tar.gz
Error: HTTP 404 NOT FOUND for url <https://pypi.io/packages/source/s/streamlit-tags/streamlit-tags-1.1.5.tar.gz>
Elapsed: 00:00.212647

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
WARNING:conda_build.source:Error: HTTP 404 NOT FOUND for url <https://pypi.io/packages/source/s/streamlit-tags/streamlit-tags-1.1.5.tar.gz>
Elapsed: 00:00.212647

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
WARNING conda_build.source:download_to_cache(84): Error: HTTP 404 NOT FOUND for url <https://pypi.io/packages/source/s/streamlit-tags/streamlit-tags-1.1.5.tar.gz>
Elapsed: 00:00.212647

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
Could not download https://pypi.io/packages/source/s/streamlit-tags/streamlit-tags-1.1.5.tar.gz

**Comment by ravinpoudel** [comment]
I tried to followed the similar approach for other package I was getting an error, and was working. I am not sure why for streamlit-tag `Error: HTTP 404 NOT FOUND` ? IF this help.

**Comment by gagan3012** [comment]
Hello, 
I have setup conda for Streamlit-tags please use:

```
conda install -c gagan3012 streamlit-tags
```

**Comment by ravinpoudel** [comment]
Thanks!!! Is it possible to make this available also at `conda-forge` channel?

**Comment by ravinpoudel** [comment]
I am still getting this error: any suggestion?
https://github.com/ravinpoudel/GuideMaker/runs/2334325249

**Comment by gagan3012** [comment]
I think it's spelled incorrectly. I have applied to be added to conda-forge

**Comment by ravinpoudel** [comment]
**> I think it's spelled incorrectly.** 

Could you provide more information ?

**Comment by gagan3012** [comment]
```
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {'streamlit-tag'}
```
The package is called `streamlit-tags` the **s** at the end is missing

**Comment by ravinpoudel** [comment]
Thanks!!!!

**Comment by gagan3012** [comment]
Is the issue resolved?

**Comment by ravinpoudel** [comment]
Yes, thanks for your help. Appreciate it a lot.

**Comment by gagan3012** [comment]
You are welcome! Please do ⭐ the repo if you liked it! Thank you!
